// y12335/src/components/FilterBar.tsx
import { useState } from 'react';
import { Search, Filter, ChevronDown } from 'lucide-react';
import { useStore } from '@/store/useStore';
import { TIME_SLOTS } from '@/data/mockData';
import { cn } from '@/lib/utils';
import type { AnomalyType } from '@/types';

const ANOMALY_OPTIONS: { value: AnomalyType; label: string }[] = [
  { value: 'vacancy', label: '空缺' },
  { value: 'skill_mismatch', label: '技能不匹配' },
  { value: 'shift_conflict', label: '班次冲突' },
  { value: 'leave_conflict', label: '请假冲突' },
];

const CATEGORY_COLORS: Record<string, string> = {
  '服务': 'bg-blue-500/20 text-blue-400',
  '安保': 'bg-red-500/20 text-red-400',
  '医疗': 'bg-rose-500/20 text-rose-400',
  '语言': 'bg-violet-500/20 text-violet-400',
  '技术': 'bg-cyan-500/20 text-cyan-400',
  '宣传': 'bg-amber-500/20 text-amber-400',
};

export { CATEGORY_COLORS };

export function FilterBar() {
  const { skills, filter, setFilter } = useStore();
  const [skillOpen, setSkillOpen] = useState(false);

  const toggleSkill = (skillId: string) => {
    const next = filter.skillIds.includes(skillId)
      ? filter.skillIds.filter(id => id !== skillId)
      : [...filter.skillIds, skillId];
    setFilter({ skillIds: next });
  };

  const toggleAnomaly = (type: AnomalyType) => {
    const next = filter.anomalyTypes.includes(type)
      ? filter.anomalyTypes.filter(t => t !== type)
      : [...filter.anomalyTypes, type];
    setFilter({ anomalyTypes: next });
  };

  const getSkillById = useStore(s => s.getSkillById);

  return (
    <div className="flex flex-wrap items-center gap-3 rounded-xl bg-surface-800 border border-surface-700 px-4 py-3">
      <Filter className="h-4 w-4 text-gray-500" />

      <div className="relative flex items-center gap-2">
        <Search className="h-4 w-4 text-gray-500" />
        <input
          type="text"
          placeholder="搜索志愿者..."
          value={filter.searchQuery}
          onChange={e => setFilter({ searchQuery: e.target.value })}
          className="w-40 rounded-lg bg-surface-700 px-3 py-1.5 text-sm text-gray-200 placeholder-gray-500 outline-none focus:ring-1 focus:ring-brand-500"
        />
      </div>

      <div className="relative">
        <button
          onClick={() => setSkillOpen(!skillOpen)}
          className="flex items-center gap-1.5 rounded-lg bg-surface-700 px-3 py-1.5 text-sm text-gray-300 hover:bg-surface-600"
        >
          技能筛选
          <ChevronDown className={cn('h-3.5 w-3.5 transition-transform', skillOpen && 'rotate-180')} />
        </button>
        {skillOpen && (
          <div className="absolute left-0 top-full z-20 mt-1 flex flex-wrap gap-1.5 rounded-lg bg-surface-800 border border-surface-700 p-3 shadow-xl">
            {skills.map(skill => (
              <button
                key={skill.id}
                onClick={() => toggleSkill(skill.id)}
                className={cn(
                  'rounded-md px-2.5 py-1 text-xs font-medium transition-colors',
                  filter.skillIds.includes(skill.id)
                    ? CATEGORY_COLORS[skill.category] || 'bg-brand-500/20 text-brand-400'
                    : 'bg-surface-700 text-gray-500 hover:text-gray-300'
                )}
              >
                {skill.name}
              </button>
            ))}
          </div>
        )}
      </div>

      {filter.skillIds.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {filter.skillIds.map(id => {
            const skill = getSkillById(id);
            if (!skill) return null;
            return (
              <span
                key={id}
                className={cn('rounded-md px-2 py-0.5 text-xs font-medium', CATEGORY_COLORS[skill.category])}
              >
                {skill.name}
                <button onClick={() => toggleSkill(id)} className="ml-1 opacity-60 hover:opacity-100">×</button>
              </span>
            );
          })}
        </div>
      )}

      <select
        value={filter.timeSlot ?? ''}
        onChange={e => setFilter({ timeSlot: e.target.value || null })}
        className="rounded-lg bg-surface-700 px-3 py-1.5 text-sm text-gray-300 outline-none focus:ring-1 focus:ring-brand-500"
      >
        <option value="">全部时段</option>
        {TIME_SLOTS.map(ts => (
          <option key={ts.id} value={ts.id}>{ts.label}</option>
        ))}
      </select>

      <div className="flex items-center gap-2 border-l border-surface-700 pl-3">
        {ANOMALY_OPTIONS.map(opt => (
          <label key={opt.value} className="flex items-center gap-1.5 text-xs text-gray-400">
            <input
              type="checkbox"
              checked={filter.anomalyTypes.includes(opt.value)}
              onChange={() => toggleAnomaly(opt.value)}
              className="accent-brand-500"
            />
            {opt.label}
          </label>
        ))}
      </div>
    </div>
  );
}

// y13065/src/components/FilterBar.vue
<script setup lang="ts">
import { Search, X, Filter, MapPin, AlertTriangle } from 'lucide-vue-next'
import type { RiskLevel } from '@/types'

defineProps<{
  zones: string[]
  currentZone: string
  statusFilter: string[]
  riskLevelFilter: string[]
  keyword: string
}>()

const emit = defineEmits<{
  (e: 'toggle-status', status: string): void
  (e: 'toggle-risk', risk: RiskLevel): void
  (e: 'set-zone', zone: string): void
  (e: 'set-keyword', kw: string): void
  (e: 'clear'): void
}>()

const statusOptions = [
  { key: 'pending', label: '待复核', color: 'bg-gray-500' },
  { key: 'passed', label: '已通过', color: 'bg-accent-pass' },
  { key: 'need-fix', label: '需修改', color: 'bg-accent-danger' },
  { key: 'overlap', label: '重叠异常', color: 'bg-accent-warning' }
]

const riskOptions = [
  { key: '高', label: '高风险', color: 'bg-red-500' },
  { key: '中', label: '中风险', color: 'bg-amber-500' },
  { key: '低', label: '低风险', color: 'bg-green-500' }
]
</script>

<template>
  <div class="bg-white border-b border-gray-200 px-6 py-3">
    <div class="flex items-center gap-4 flex-wrap">
      <div class="flex items-center gap-2">
        <Filter class="w-4 h-4 text-gray-500" />
        <span class="text-sm font-medium text-gray-700">筛选：</span>
      </div>

      <div class="flex items-center gap-1.5">
        <button
          v-for="opt in statusOptions"
          :key="opt.key"
          class="chip"
          :class="{ 'chip-active': statusFilter.includes(opt.key) }"
          @click="emit('toggle-status', opt.key)"
        >
          <span :class="[opt.color, 'w-2 h-2 rounded-full']"></span>
          {{ opt.label }}
        </button>
      </div>

      <div class="h-5 w-px bg-gray-300 mx-1"></div>

      <div class="flex items-center gap-1.5">
        <MapPin class="w-3.5 h-3.5 text-gray-500" />
        <button
          class="chip"
          :class="{ 'chip-active': !currentZone }"
          @click="emit('set-zone', '')"
        >
          全部区域
        </button>
        <button
          v-for="z in zones"
          :key="z"
          class="chip"
          :class="{ 'chip-active': currentZone === z }"
          @click="emit('set-zone', z)"
        >
          {{ z }}
        </button>
      </div>

      <div class="h-5 w-px bg-gray-300 mx-1"></div>

      <div class="flex items-center gap-1.5">
        <AlertTriangle class="w-3.5 h-3.5 text-gray-500" />
        <button
          class="chip"
          :class="{ 'chip-active': riskLevelFilter.length === 0 }"
          @click="emit('toggle-risk', '高'); emit('toggle-risk', '中'); emit('toggle-risk', '低')"
          v-if="riskLevelFilter.length > 0"
        >
          全部风险
        </button>
        <button
          v-for="opt in riskOptions"
          :key="opt.key"
          class="chip"
          :class="{ 'chip-active': riskLevelFilter.includes(opt.key) }"
          @click="emit('toggle-risk', opt.key)"
        >
          <span :class="[opt.color, 'w-2 h-2 rounded-full']"></span>
          {{ opt.label }}
        </button>
      </div>

      <div class="h-5 w-px bg-gray-300 mx-1"></div>

      <div class="relative">
        <Search class="w-4 h-4 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" />
        <input
          :value="keyword"
          @input="emit('set-keyword', ($event.target as HTMLInputElement).value)"
          type="text"
          placeholder="搜索吊杆或批注内容..."
          class="pl-9 pr-8 py-1.5 text-sm border border-gray-300 rounded-engineer w-64 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:border-primary"
        />
        <button
          v-if="keyword"
          class="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
          @click="emit('set-keyword', '')"
        >
          <X class="w-3.5 h-3.5" />
        </button>
      </div>

      <div class="flex-1"></div>

      <button
        v-if="statusFilter.length || currentZone || keyword || riskLevelFilter.length"
        class="text-xs text-gray-500 hover:text-primary underline"
        @click="emit('clear')"
      >
        清空筛选
      </button>
    </div>
  </div>
</template>
